export default {
  title: "LOLCAT CLOCK",
  title2: "I CAN HAZ TIME??",
  english: "English",
  portuguese: "Portuguese",
  messageParty: "Let's party!",
  messageWakeUp: "Wake up!",
  messageLunch: "Let's have some lunch!",
  messageSleep: "Sleep tight!",
  messageStdMorning: "Good morning!",
  messageStdEvening: "Good evening!",
  messageStdAfternoon: "Good afternoon!",
  partyButtonText: "PARTY TIME!",
  partyOver: "PARTY OVER!",
  wakeUpTimeMessage: "set Wake Up time",
  lunchTimeMessage: "set Lunch time",
  napTimeMessage: "set Nap time", 
};
